//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirstWebApplication.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Data
    {
        public int ID { get; set; }
        public string Title { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<int> Cost { get; set; }
    }
}
